### ISSUE TITLE
Thanks and install question..

### ISSUE THREAD

**Issue by champagj** [magcode/mopidy-mixcloudsimple#1]
Working on a mopidy-based raspberry using iris.
I need mostly soundcloud and mixcloud support, not so much spotify.
Your PR on iris to get mixcloud support got me here. Big thanks, works great.

On install
_sudo python3 pip install -e mopidy-mixcloudsimple_

did not work for me. I had to use

_sudo pip3 install -e mopidy-mixcloudsimple__

Thanks again

**Comment by magcode** [comment]
Glad you like it!
I added a hint to the readme regarding the installation. Thanks.

When using iris be aware that iris [does not have a UI to refresh the library](https://github.com/jaedb/Iris/issues/556).
At the moment you need another client to refresh the mixcloud tracks.


I might implement a simple TTL of one day.
